apiVersion: apps/v1
kind: Deployment
metadata:
 name: vue-app
spec:
 replicas: {{ .Values.replicaCount }}
 selector:
   matchLabels:
     app: {{ .Values.app.name }}
 template:
   metadata:
     labels:
       app: {{ .Values.app.name }}
   spec:
     containers:
     - name: {{ .Values.container.name }}
       image: {{ .Values.image.repository }}
       imagePullPolicy: {{ .Values.image.pullPolicy }}
       ports:
       - containerPort: 80